source "https://rubygems.org"

gem "github-pages", "~> 232", group: :jekyll_plugins

gem "tzinfo-data"
# gem "wdm", "~> 0.1.0" if Gem.win_platform? # I don't think we need that?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate", "~> 1.1.0"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-gist", "~> 1.5.0"
  # gem "jekyll-feed", "~> 0.17.0"
  gem "jemoji", "~> 0.13.0"
  gem "jekyll-include-cache", "~> 0.2.1"
  gem "jekyll", "~> 3.10.0"
end
